### PR TITLE
Fix broken references in deprecation docs

### PR DESCRIPTION
**Pull request by cgmb**
This change fixes Sphinx errors like:

> doxygentypedef: Cannot find typedef “rocsolver_int” in doxygen xml output for project “rocSOLVER” from directory: ../docBin/xml

that were introduced by #298. You can see the errors on [the 'latest' version of the docs](https://rocsolver.readthedocs.io/en/latest/api_deprecated.html#rocsolver-int).

Issue: SWDEV-298025 (HOTFIX)

### CODE REVIEW

**Review by tfalders — APPROVED** [review]

**Review by jzuniga-amd — APPROVED** [review]

**Comment by doctorcolinsmith** [comment]
@lawruble13 I think you have already fixed the error showing on CI.  Can you please confirm that it is fixed and re-run the CI jobs?
