### ISSUE TITLE
Cannot include rocsolver.h from C code in ROCm 3.7

### ISSUE THREAD

**Issue by kruger** [ROCmSoftwarePlatform/rocSOLVER#149]
When using `rocsolver.h` from c code in ROCm 3.5 (needed just go get the handle type at a minimum), there are errors many errors related to the `pivot = 1` arguments:

```
/opt/rocm/include/rocsolver-functions.h:2548:76: error: C does not support default arguments
                                                   const rocblas_int pivot = 1);
```

This did not occur in ROCm 3.5 of course.

Submitted by member of CoE Frontier team.

**Comment by cgmb** [comment]
Sorry about that! This was fixed in 419eae8877d802017923560079a6f31910b6e07b and a test to prevent regression was added in afade515ad99dc3c486d08fbfb2c29d8625811bb. I think those are in ROCm 3.8.

**Comment by kruger** [comment]
Is there going to be a 3.7.1 release with rpms/pkgs that have this fix?

**Comment by doctorcolinsmith** [comment]
@kruger At this time, there is not a 3.7.1 release planned.  ROCm 3.8 is getting tested and prepared for release.

**Comment by cgmb** [comment]
The 3.8 release is just around the corner, but if you're looking for a workaround right now, you could supply a fixed header with the default values removed. That can be done without changing the installed package by including a header containing the fix before `rocsolver.h`. There's two steps to create such a header:

1. Create a `rocsolver-functions-3.7-issue149-workaround.h` file without those default values.

    sed 's/pivot = 1/pivot/' /opt/rocm-3.7.0/include/rocsolver-functions.h > rocsolver-functions-3.7-issue149-workaround.h

2.  Modify the header so can stand on its own. Save the patch below as `workaround.patch` in the same directory as `rocsolver-functions-3.7-issue149-workaround.h` and apply with `patch < workaround.patch`
```
--- rocsolver-functions-3.7-issue149-workaround.h.old	2020-09-10 04:37:13.026938460 +0000
+++ rocsolver-functions-3.7-issue149-workaround.h	2020-09-10 04:50:01.234781437 +0000
@@ -2,6 +2,10 @@
  * Copyright 2019-2020 Advanced Micro Devices, Inc.
  * ************************************************************************ */
 
+#include "rocsolver-version.h"
+#if ((ROCSOLVER_VERSION_MAJOR == 3) && (ROCSOLVER_VERSION_MINOR == 7) && (ROCSOLVER_VERSION_PATCH == 0))
+#include "rocsolver-export.h"
+
 #ifndef _ROCLAPACK_FUNCTIONS_H
 #define _ROCLAPACK_FUNCTIONS_H
 
@@ -5594,3 +5598,5 @@
 #endif
 
 #endif /* _ROCLAPACK_FUNCTIONS_H */
+
+#endif /* ROCSOLVER_VERSION */
```

Including `rocsolver-functions-3.7-issue149-workaround.h` before `rocsolver.h` in our sample C program and compiling with `/opt/rocm/bin/hipcc -I/opt/rocm/include -D__HIP_PLATFORM_HCC__=1 -c sample.c` works on my ROCm 3.7 install.

**Comment by kruger** [comment]
Thanks!

**Comment by cgmb** [comment]
I've verified this is fixed in ROCm 3.8.0.
